Vagrant.configure(2) do |config|
  config.vm.box = "box-cutter/ubuntu1404-desktop"
  config.vm.network :forwarded_port, host: 4000, guest: 4000
  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "2048"
     vb.name = "ICSE-2014-Verily"
   end
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get -y install openjdk-7-jdk
     sudo apt-get -y install maven
     sudo gsettings set org.gnome.desktop.screensaver lock-enabled false
  SHELL
end