Vagrant.configure(2) do |config|
  #Getting Ubuntu 14.04 64bit Desktop base-box
  config.vm.box = "box-cutter/ubuntu1404-desktop"
  #Configuring Network for Verily
  config.vm.network :forwarded_port, host: 4000, guest: 4000
  config.vm.provider "virtualbox" do |vb|
    #Enabling GUI
     vb.gui = true
    #Setting Memory for VM
     vb.memory = "2048"
    #Setting VM Name
     vb.name = "ICSE-2014-Verily"
   end
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
    #Installing Java
     sudo apt-get -y install openjdk-7-jdk
    #Installing Maven
     sudo apt-get -y install maven
    #Disabling Screenlock on Idle
     sudo gsettings set org.gnome.desktop.screensaver lock-enabled false
  SHELL
end
